using Pkg
Pkg.add([
    "Distributions",
    "LinearAlgebra",
    "Parameters",
    "Plots",
    "BifurcationKit",
    "DifferentialEquations",
    "BenchmarkTools",
    "CSV",
    "Tables",
    "BenchmarkPlots",
    "StatsPlots",
    "Accessors",
    "NaNMath",
    "LaTeXStrings",
    "Optim",
    "DataFrames",
    ]
)
